.gitignore, app/auth/login/page.tsx, app/home/settings/page.tsx, components/molecules/CompanyDataForm.tsx, components/molecules/Navigation.tsx, lib/supabase/auth.ts, lib/supabase/server.ts, middleware.ts, pnpm-lock.yaml
Here, the toast was deleted and replaced by the red banner shown at the very top of the page
=> Show banner at the very top of the settings page telling the user the company data is still required to go ahead

app/home/settingsv2/layout.tsx, app/home/settingsv2/page.tsx, app/home/settingsv2/security/page.tsx, components/molecules/CompanyDataForm.tsx, lib/supabase/client-utils.ts, lib/supabase/middleware.ts, lib/supabase/routeRestrictionsLists.ts, lib/supabase/server.ts, middleware.ts
The issue was in the middleware code.
The Supabase client instance wasn't given the methods for correctly writing cookies. Additionally, some improvements on code readability were added, even though it's still open to improvement
=> Correct session synchronization 

app/home/invoices/page.tsx, components/molecules/CreateInvoiceButton.tsx, components/molecules/InvoiceView2.tsx, components/molecules/InvoicesTable.tsx, components/molecules/Navigation.tsx, lib/supabase/services/invoice.ts
Reason: Since several fields are not registered on React Hook Form, using setValue on them doesn't make any sense. So, we had to manually compute those values and add it to the final invoice
=> Compute invoice data and add it to the invoice object to be sent to database

.gitignore, components/molecules/CreateInvoiceButton.tsx, components/molecules/InvoiceView2.tsx, package.json, pnpm-lock.yaml
Now date for invoices is being stored as complete zoned timestamp, but render PDF function is expecting DD/MM/YYYY format (Which we must fix later)
=> Fix(invoice) Date saved ad complete timestamp and passed date part for PDF render

app/auth/signup/page.tsx, lib/supabase/auth.ts
=> Fixes#50 Register user

components/molecules/InvoiceView2.tsx, components/organisms/invoices/InvoicePreview.tsx
=> [issue#59] Show company logo on preview invoice

app/home/customers/page.tsx, app/home/products-v2/page.tsx, lib/supabase/services/BaseService.ts, lib/supabase/services/product.ts, utils/tableColumns.ts
=> Fix delete product

app/home/customers/page.tsx, lib/supabase/services/customer.ts, lib/supabase/services/product.ts, utils/tableColumns.ts
=> fix#58: Allow Edit Customers

components/molecules/InvoiceView2.tsx, components/organisms/invoices/InvoiceForm.tsx, components/organisms/invoices/InvoicePreview.tsx, components/ui/date-picker.tsx, lib/supabase/services/company.ts
Closes #68 
and also Fixes issue with formatting company limit date of authorized invoice number
=> Fix 68 Date Picker on Invoice creation and limit_date on company

components/organisms/invoices/InvoiceForm.tsx, lib/supabase/services/invoice.ts
=> [Fix#72] Remove requirement for email on generate invoice

app/home/products-v2/register-order/page.tsx, components/molecules/DataGrid.tsx, components/ui/input.tsx, lib/supabase/services/product.ts, package.json, pnpm-lock.yaml
=> fix#76: Add Reason to update inventory and validations

components/molecules/invoiceProductInputs/ProductSelect.tsx, components/organisms/invoices/InvoiceForm.tsx, components/organisms/invoices/InvoicePreview.tsx
=> Issue 67 invoice add product table re-styling

app/globals.css, app/home/products-v2/page.tsx, components/molecules/DataGrid.tsx, components/organisms/products/ProductImportStepper.tsx, components/ui/switch.tsx, hooks/useUploadXls.ts, package.json, pnpm-lock.yaml, supabase/funcions/update_product_stock_v2.sql
=> fix#55: Implement stepper for bulk import

app/home/invoices/page.tsx, components/molecules/InvoicesTable.tsx
=> Fix#79: Quick filter fix

app/home/customers/page.tsx, components/molecules/CustomerForm.tsx
=> Fix#74: Contacts form redesign

app/home/load-data/page.tsx, components/molecules/CreateInvoiceButton.tsx, lib/supabase/services/product.ts, utils/providers/ReactQueryProvider.tsx
=> Fix#82: Create Invoice Error of no products

app/home/products-v2/register-order/page.tsx, components/molecules/DataGrid.tsx
=> [Fix#86]: Discard register order changes

app/home/invoices/create-invoice/page.tsx, app/home/invoices/page.tsx, app/home/page.tsx, app/home/products-v2/page.tsx, components/molecules/CaiExpirationWarning.tsx, components/molecules/CompanyDataForm.tsx, components/molecules/CreateInvoiceButton.tsx, components/molecules/InvoiceView2.tsx, components/organisms/invoices/InvoiceForm.tsx, components/ui/alert.tsx, lib/supabase/services/BaseService.ts, lib/supabase/services/company.ts, lib/supabase/services/invoice.ts, lib/supabase/services/sar_cai.ts, utils/providers/ReactQueryProvider.tsx
Fixes #105 
* Actualizar rango de facturacion
* Usar rango activo en invoice
* Buscar ultimo invoice number del rango activo
* Agregar validations
* Mostrar mensaje de expiracion de CAI
=> Issue #105 CAI Update

app/auth/login/page.tsx, app/auth/signup/page.tsx
=> fix#111: Email copies on login/signup

app/auth/signup/page.tsx
=> Fix#110: RTN format on signup

app/home/products-v2/register-order/page.tsx, hooks/useSupabaseAuth.ts, lib/supabase/services/BaseService.ts, lib/supabase/services/product.ts
=> fix#85: Filter out services from register product table

app/home/customers/page.tsx, components/organisms/invoices/InvoiceForm.tsx, lib/supabase/services/BaseService.ts, lib/supabase/services/customer.ts
=> Fix#66: Soft delete customer

app/home/products-v2/register-order/page.tsx
=> Issue 84 register order

components/molecules/DataGrid.tsx
=> Fix#87: onBlur cell apply changes

app/auth/signup/page.tsx, components/login-form.tsx
=> fix#122: change terms and conditions url

app/auth/confirm-email/page.tsx
=> fix#121: Signup confirmation copy

components/molecules/CompanyDataForm.tsx
=> Fix#124: Phone number mask on config

components/organisms/InvoiceDashboardCharts.tsx
=> fix#90: filter out cancelled invoices

components/molecules/CustomerForm.tsx
=> Fix#101: Contact card email and phone

components/organisms/invoices/InvoiceForm.tsx, lib/supabase/services/BaseService.ts, lib/supabase/services/customer.ts
=> Fix#125: Default to Consumidor Final and Show current selected

components/molecules/CompanyDataForm.tsx
=> Fix#140: Icon trigger submit

app/home/layout.tsx, components/organisms/invoices/InvoiceForm.tsx
=> fix#133: remove exenta option

app/home/page.tsx, components/organisms/InvoiceDashboardChartsV2.tsx, lib/supabase/services/invoice.ts
=> Fix#141: Dashboard Charts calc logic

app/globals.css, components/organisms/InvoiceDashboardChartsV2.tsx
=> Issue 149 dashboard fixes

app/home/invoices/page.tsx, lib/supabase/services/invoice.ts
=> Fix#150: Fix monthly revenue on invoices

components/app-sidebar/app-sidebar.tsx, components/app-sidebar/nav-user.tsx
=> Fix#161: User Nav hover

components/molecules/InvoiceViewPdf.tsx
=> Fix#162: Proforma number on PDF

app/home/customers/page.tsx, components/molecules/DataGrid.tsx, utils/tableColumns.ts
=> Fix#166: Prevent delete Consumidor Final

app/home/layout.tsx, components/app-sidebar/nav-user.tsx
=> Fix#163: Default open sidebar

app/home/invoices/create-invoice/page.tsx, components/molecules/CaiExpirationWarning.tsx, components/molecules/CompanyDataForm.tsx, components/molecules/CreateInvoiceButton.tsx, components/organisms/invoices/InvoiceForm.tsx, components/organisms/invoices/NewInvoiceLoadingSkeleton.tsx, lib/supabase/services/sar_cai.ts
=> Issue 159 invoice mode
